<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="CompanyDatabase.aspx.cs" Inherits="Project.NET.CompanyDatabase" %>
<!--
   1.GridView:  Displays tabular data in ASP.NET. It allows users to perform CURD operations on a database.
   2.BoundField: Displays data in a read-only format within the GridView.It binds a column in the GridView to a database field.
   3.DataField: Binds to the  column from the database.
   4.HeaderText: Sets the column name to be displayed in the GridView.
   5.ConnectionString: Connects the application to a database.Contains database server name, database name, and authentication details.
   6.Data Source: Specifies the SQL Server name.
   7.Initial Catalog: Specifies the database name.
   8.Integrated Security=True:  Uses Windows authentication.
   9.SelectCommand: Fetches data from the Employees table.
  10.DeleteCommand: Deletes a record based on EmployeeID.
  11.UpdateCommand: Updates selected fields in the Employees table.
  12.Parameters: Used in SqlDataSource to update records dynamically. 
     -->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<title>COMPANY DATABASE</title>
   
</head>
<body>
    <form id="form1" runat="server">
      <div>
        <h1 runat="server">Compnay Database </h1>
          
          
          <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" DataKeyNames="EmployeeID" DataSourceID="SqlDataSource1" AutoGenerateDeleteButton="true" AutoGenerateEditButton="True" AllowSorting="True" AllowPaging="True" PageSize="10" >
                
              <Columns>
                    <asp:BoundField DataField="EmployeeID" HeaderText="EmployeeID" ReadOnly="True" />
                    <asp:BoundField DataField="FirstName" HeaderText="First Name" />
                    <asp:BoundField DataField="LastName" HeaderText="Last Name" />
                    <asp:BoundField DataField="DateOfBirth" HeaderText="Date Of Birth" DataFormatString="{0:yyyy-MM-dd}" />
                    <asp:BoundField DataField="Email" HeaderText="Email" />
                    <asp:BoundField DataField="PhoneNumber" HeaderText="Phone Number" />
                    <asp:BoundField DataField="Address" HeaderText="Address" />
                    <asp:BoundField DataField="HireDate" HeaderText="Hire Date" DataFormatString="{0:yyyy-MM-dd}" />
                    <asp:BoundField DataField="JobTitle" HeaderText="Job Title" />
                    <asp:BoundField DataField="DepartmentID" HeaderText="Department ID" />
                    <asp:BoundField DataField="Salary" HeaderText="Salary" />
                    <asp:BoundField DataField="ManagerID" HeaderText="Manager ID" />
                   </Columns>

            </asp:GridView>

               <asp:SqlDataSource ID="SqlDataSource1" runat="server"
                  ConnectionString="<%$ ConnectionStrings:CompanyDB %>"
                  SelectCommand="SELECT EmployeeID, FirstName, LastName, DateOfBirth, Email, PhoneNumber, Address, HireDate, JobTitle, DepartmentID, Salary, ManagerID FROM Employees;"
                  DeleteCommand="DELETE FROM Employees WHERE EmployeeID=@EmployeeID;"
                  UpdateCommand="UPDATE Employees SET FirstName=@FirstName, LastName=@LastName, DateOfBirth=@DateOfBirth, Email=@Email, PhoneNumber=@PhoneNumber, Address=@Address, HireDate=@HireDate, JobTitle=@JobTitle, DepartmentID=@DepartmentID, Salary=@Salary, ManagerID=@ManagerID WHERE EmployeeID=@EmployeeID;">
                
                   <UpdateParameters>

                    <asp:Parameter Name="FirstName" Type="String" />
                    <asp:Parameter Name="LastName" Type="String" />
                    <asp:Parameter Name="DateOfBirth" Type="DateTime" />
                    <asp:Parameter Name="Email" Type="String" />
                    <asp:Parameter Name="PhoneNumber" Type="String" />
                    <asp:Parameter Name="Address" Type="String" />
                    <asp:Parameter Name="HireDate" Type="DateTime" />
                    <asp:Parameter Name="JobTitle" Type="String" />
                    <asp:Parameter Name="DepartmentID" Type="Int32" />
                    <asp:Parameter Name="Salary" Type="Decimal" />
                    <asp:Parameter Name="ManagerID" Type="Int32" />
                    <asp:Parameter Name="EmployeeID" Type="Int32" />
                
                   </UpdateParameters>
                   <DeleteParameters>
                     <asp:Parameter Name="FirstName" Type="String" />
                     <asp:Parameter Name="LastName" Type="String" />
                     <asp:Parameter Name="DateOfBirth" Type="DateTime" />
                     <asp:Parameter Name="Email" Type="String" />
                     <asp:Parameter Name="PhoneNumber" Type="String" />
                     <asp:Parameter Name="Address" Type="String" />
                     <asp:Parameter Name="HireDate" Type="DateTime" />
                     <asp:Parameter Name="JobTitle" Type="String" />
                     <asp:Parameter Name="DepartmentID" Type="Int32" />
                     <asp:Parameter Name="Salary" Type="Decimal" />
                     <asp:Parameter Name="ManagerID" Type="Int32" />
                     <asp:Parameter Name="EmployeeID" Type="Int32" />
                   </DeleteParameters>

            </asp:SqlDataSource>
               <br />
            <asp:Button ID="BtnRegisterPage" runat="server" Text="Go to Register Page" OnClick="BtnRegisterPage_Click" />
        </div>
    </form>
</body>
</html>
